name: e_commerce
description: "A new Flutter project."

# Prevent accidental publication to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility packages

  # Icons
  iconsax: any
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting for good coding practices
  flutter_lints: ^4.0.0

flutter:
  # Include Material Icons font
  uses-material-design: true

  # Local assets
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/

  # Custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
        
